### ISSUE TITLE
Issue Module LINE

### ISSUE THREAD

**Issue by winlianclub** [merkremont/LineChivas#13]
@merkremont help me please

python chivasbot.py
Traceback (most recent call last):
  File "chivasbot.py", line 7, in <module>
    cl = LineAlpha.LINE()
AttributeError: 'module' object has no attribute 'LINE'

**Comment by Gabrieeeltd** [comment]
Lmao, i got this 

```
Traceback (most recent call last):
  File "chivasbot.py", line 8, in <module>
    cl.login(qr=True)
  File "C:\Users\user\LineChivas\LineAlpha\LineApi.py", line 33, in login
    self.Talk.qrLogin(callback)
  File "C:\Users\user\LineChivas\LineAlpha\Api\Talk.py", line 89, in qrLogin
    qr = self.client.getAuthQrcode(True, "Chivas-PC")
  File "C:\Users\user\LineChivas\LineAlpha\Gen\LineService.py", line 9273, in getAuthQrcode
    return self.recv_getAuthQrcode()
  File "C:\Users\user\LineChivas\LineAlpha\Gen\LineService.py", line 9286, in recv_getAuthQrcode
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "C:\Python27\lib\site-packages\thrift\protocol\TCompactProtocol.py", line 310, in readMessageBegin
    proto_id = self.__readUByte()
  File "C:\Python27\lib\site-packages\thrift\protocol\TCompactProtocol.py", line 289, in __readUByte
    result, = unpack('!B', self.trans.readAll(1))
  File "C:\Python27\lib\site-packages\thrift\transport\TTransport.py", line 63, in readAll
    raise EOFError()
EOFError
```

:')

**Comment by howart113** [comment]
Bot

**Comment by winlianclub** [comment]
Please closed this issue cause u never shared full your skill... thanks
