### ISSUE TITLE
can you help me ?

### ISSUE THREAD

**Issue by yekayee** [merkremont/LineChivas#2]
Traceback (most recent call last):
  File "LineApi.py", line 2, in <module>
    from Api import Poll, Talk, channel
  File "C:\Users\kaye\Desktop\LineChivas-master\LineAlpha\Api\__init__.py", line
 1, in <module>
    from Talk import Talk
  File "C:\Users\kaye\Desktop\LineChivas-master\LineAlpha\Api\Talk.py", line 3,
in <module>
    import requests, rsa
ImportError: No module named requests

**Comment by merkremont** [comment]
Install python packages _requests_
`$ pip install requests`

**Comment by yekayee** [comment]
C:\line>python chivasbot.py
line://au/q/VKSwkSDkN0vnRNS4vUPjgVhiUmhcJMZO
Traceback (most recent call last):
  File "chivasbot.py", line 8, in <module>
    cl.login(qr=True)
  File "C:\line\LineAlpha\LineApi.py", line 33, in login
    self.Talk.qrLogin(callback)
  File "C:\line\LineAlpha\Api\Talk.py", line 97, in qrLogin
    vr = r.json()["result"]["verifier"]
KeyError: 'result'

**Comment by yekayee** [comment]
can you help me again ? :+1:

**Comment by merkremont** [comment]
@yekayee 
You have to login with QR Link that showed from terminal/command prompt
and attach to your LINE Apps

**Comment by yekayee** [comment]
how ? you have video ?
im not understand dude :(

**Comment by yekayee** [comment]
@merkremont 
Login qrcode to your smartphone in 2 minutes
line://au/q/KYZkyEF1ieqRA16SfWjEcHm6qTgrWWuG

how to login ?

**Comment by merkremont** [comment]
@yekayee 
Copy to your LINE chat from LINE for PC, then click the link at your phone from LINE app

**Comment by yekayee** [comment]
okay thankss,,

**Comment by yekayee** [comment]
@merkremont 
certificate :

name : Dino Achmad Feranza
None

not run :(

**Comment by yekayee** [comment]
you have id line dude ? 
@merkremont

**Comment by rizqiqiqi** [comment]
help use termux android, 


r00t™@localhost:~/LineChivas $ python2 chivasbot.py
Traceback (most recent call last):
  File "chivasbot.py", line 2, in <module>
    import LineAlpha
  File "/data/data/com.termux/files/home/LineChivas/LineAlpha/__init__.py", line 2, in <module>
    from LineApi import LINE
  File "/data/data/com.termux/files/home/LineChivas/LineAlpha/LineApi.py", line 2, in <module>
    from Api import Poll, Talk, channel
  File "/data/data/com.termux/files/home/LineChivas/LineAlpha/Api/__init__.py", line 1, in <module>
    from Talk import Talk
  File "/data/data/com.termux/files/home/LineChivas/LineAlpha/Api/Talk.py", line 3, in <module>
    import requests, rsa
ImportError: No module named requests

**Comment by rizqiqiqi** [comment]
Yes i can login.how to try this bot?

**Comment by merkremont** [comment]
@yekayee 
No, Send me a dm on my [twitter](https://twitter.com/merkremont)

@rizqiqiqi 
Type a command on chat room
