### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by winlianclub** [merkremont/LineChivas#20]
Help me please for this issue

F:\LINEBOT\LineChivas (master)
λ python chivasbot.py
Traceback (most recent call last):
  File "chivasbot.py", line 2, in <module>
    import LineAlpha
  File "F:\LINEBOT\LineChivas\LineAlpha\__init__.py", line 2, in <module>
    from LineApi import LINE
  File "F:\LINEBOT\LineChivas\LineAlpha\LineApi.py", line 2, in <module>
    from Api import Poll, Talk, Channel
  File "F:\LINEBOT\LineChivas\LineAlpha\Api\__init__.py", line 3, in <module>
    from channel import Channel
  File "C:\Python27\lib\site-packages\channel.py", line 3
    print('This is suroegin's package - channel')
                            ^
SyntaxError: invalid syntax

**Comment by winlianclub** [comment]
-= UPDATE ISSUE =-

F:\LINEBOT\LineChivas (master)
λ python chivasbot.py
line://au/q/ETRJch28Jr5ZLXSPQkTXPpuNuI0v7O9R
Traceback (most recent call last):
  File "chivasbot.py", line 8, in <module>
    cl.login(qr=True)
  File "F:\LINEBOT\LineChivas\LineAlpha\LineApi.py", line 33, in login
    self.Talk.qrLogin(callback)
  File "F:\LINEBOT\LineChivas\LineAlpha\Api\Talk.py", line 94, in qrLogin
    "X-Line-Access": qr.verifier,
  File "C:\Python27\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //gd2.line.naver.jp/Q (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0000000003556A90>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

help me please...

**Comment by winlianclub** [comment]
Sorry, how to resolve this problem ??? and thanks before for support :D :D :D

**Comment by howart113** [comment]
Bot

**Comment by winlianclub** [comment]
Please closed this issue cause u never shared full your skill... thanks
