### ISSUE TITLE
another error. cant login

### ISSUE THREAD

**Issue by kirwinkk** [merkremont/LineChivas#25]
python2 chivasbot.py
line://au/q/v1Leb9iDVjplQWrBb5SgqbnSPWAzJ604
Traceback (most recent call last):
  File "chivasbot.py", line 8, in <module>
    cl.login(qr=True)
  File "/data/data/com.termux/files/home/LineChivas/LineAlpha/LineApi.py", line 33, in login
    self.Talk.qrLogin(callback)
  File "/data/data/com.termux/files/home/LineChivas/LineAlpha/Api/Talk.py", line 94, in qrLogin
    "X-Line-Access": qr.verifier,
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //gd2.line.naver.jp:443/Q (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5ae7dd0>: Failed to establish a new connection: [Errno 7] No address associated with hostname',))

**Comment by winlianclub** [comment]
Me too have a same problem like you @kirwinkk , help us @merkremont and @fadhiilrachman for this issue please

**Comment by winlianclub** [comment]
Please closed this issue cause u never shared full your skill... thanks
