### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by yuvihi** [merkremont/LineChivas#26]
line://au/q/bL9F3STAuLQ12nCuszqwp9UnW5vjh2ui
Traceback (most recent call last):
  File "C:\Users\yovap\Desktop\LineChivas-master\chivasbot.py", line 8, in <module>
    cl.login(qr=True)
  File "C:\Users\yovap\Desktop\LineChivas-master\LineAlpha\LineApi.py", line 33, in login
    self.Talk.qrLogin(callback)
  File "C:\Users\yovap\Desktop\LineChivas-master\LineAlpha\Api\Talk.py", line 94, in qrLogin
    "X-Line-Access": qr.verifier,
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //gd2.line.naver.jp:443/Q (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000000367B128>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

what will I do ? :"(

**Comment by tetsuyaPrince** [comment]
use termux on your device ..
i can't understand for using personal computer.. 😂😂

**Comment by winlianclub** [comment]
PM me ID : winlian

**Comment by yuvihi** [comment]
cd
$ cd LineChivas && python2 chivasbot.py
line://au/q/LFLzhumtm3fRjnWBd5oqyDJRLPwYEpWG
Traceback (most recent call last):
  File "chivasbot.py", line 8, in <module>
    cl.login(qr=True)
  File "/data/data/com.termux/files/home/LineChivas/LineAlpha/LineApi.py", line 33, in login
    self.Talk.qrLogin(callback)
  File "/data/data/com.termux/files/home/LineChivas/LineAlpha/Api/Talk.py", line 94, in qrLogin
    "X-Line-Access": qr.verifier,
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, send_kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //gd2.line.naver.jp:443/Q (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f78d750>: Failed to establish a new connection: [Errno 7] No address associated with hostname',))
$

**Comment by merkremont** [comment]
We have fixed now

**Comment by yuvihi** [comment]
can't login

cd LineChivas && python2 chivasbot.py
line://au/q/n70AEI2uHCzvkp7Tn5cYdrDFAqllOQMq
Traceback (most recent call last):
  File "chivasbot.py", line 8, in <module>
    cl.login(qr=True)
  File "/data/data/com.termux/files/home/LineChivas/LineAlpha/LineApi.py",
line 41, in login
    self.channel = channel.Channel(self.authToken)
NameError: global name 'channel' is not defined
$

**Comment by merkremont** [comment]
We have fixed now, try to update this git @yuvihi
