### ISSUE TITLE
LOGIN ISSUE...

### ISSUE THREAD

**Issue by fhrzx** [merkremont/LineChivas#28]
# What should i do?

**_python chivasbot.py
line://au/q/Ze4yOkp4wz0NIRYbyqXFQhM3kRUmkUvy
Traceback (most recent call last):
  File "chivasbot.py", line 8, in <module>
    cl.login(qr=True)
  File "C:\Users\XXXX\LineChivas\LineAlpha\LineApi.py", line 33, in login
    self.Talk.qrLogin(callback)
  File "C:\Users\XXXX\LineChivas\LineAlpha\Api\Talk.py", line 94, in qrLogin
    "X-Line-Access": qr.verifier,
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //gd2.line.naver.jp:443/Q (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x047868B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))_**

## # Can anyone help me?

**Comment by winlianclub** [comment]
Pm me ID : winlian

**Comment by fhrzx** [comment]
@winlianclub Nope, you can't even fix the script...

**Comment by moepoi** [comment]
@winlianclub mana bisa fix, cuma jago bilang script orang sampah 😉

**Comment by arisawali2014** [comment]
@fhrzx LOL 😂

**Comment by winlianclub** [comment]
@moepoi kasihan deh lo

**Comment by merkremont** [comment]
We have fixed now
