### ISSUE TITLE
Error LineChivas

### ISSUE THREAD

**Issue by winlianclub** [merkremont/LineChivas#6]
Help me please @merkremont  for this error

[root@sgx LineChivas]# python chivasbot.py
/root/LineChivas/LineAlpha/Api/Talk.py:27: DeprecationWarning: Please use the THttpClient('http://host:port/path') syntax
  self.transport = THttpClient.THttpClient(self.host, self.port, self.http_query_path)
line://au/q/RHoydtLpohG02yU5qauogQ6GUISzTuMb
Traceback (most recent call last):
  File "chivasbot.py", line 8, in <module>
    cl.login(qr=True)
  File "/root/LineChivas/LineAlpha/LineApi.py", line 33, in login
    self.Talk.qrLogin(callback)
  File "/root/LineChivas/LineAlpha/Api/Talk.py", line 98, in qrLogin
    lr = self.client.loginWithVerifierForCerificate(vr)
  File "/root/LineChivas/LineAlpha/Gen/LineService.py", line 11189, in loginWithVerifierForCerificate
    self.send_loginWithVerifierForCerificate(verifier)
  File "/root/LineChivas/LineAlpha/Gen/LineService.py", line 11196, in send_loginWithVerifierForCerificate
    args.write(self._oprot)
  File "/root/LineChivas/LineAlpha/Gen/LineService.py", line 61628, in write
    oprot.writeString(self.verifier)
  File "build/bdist.linux-x86_64/egg/thrift/protocol/TProtocol.py", line 121, in writeString
  File "build/bdist.linux-x86_64/egg/thrift/protocol/TCompactProtocol.py", line 42, in nested
  File "build/bdist.linux-x86_64/egg/thrift/protocol/TCompactProtocol.py", line 272, in __writeBinary
  File "build/bdist.linux-x86_64/egg/thrift/transport/THttpClient.py", line 134, in write
TypeError: expecting a bytes object, got unicode

**Comment by winlianclub** [comment]
Sorry i don't understand... can you help me ???
